name: cords2023
channels:
- fastai
- conda-forge
- defaults
dependencies:
- python=3.9
- pip
- ipykernel
- numpy
- matplotlib
- pandas
- scipy
- scikit-learn
- numba
- ngboost
- statsmodels
- pip:
  - mip
